"use client";

import { useState } from "react";

const glossary = [
  { term: "Interchange (IC)", definition: "The base fee set by card networks (Visa, Mastercard) that goes to the card-issuing bank. This is the non-negotiable floor of card processing costs." },
  { term: "IC+ (Interchange Plus)", definition: "A transparent pricing model where you pay actual interchange plus a fixed markup. The most honest way to price card processing — you see exactly what goes to the network vs. your processor." },
  { term: "Flat Rate", definition: "A single percentage charged on every transaction regardless of card type. Simple to understand but typically more expensive — you overpay on debit and standard cards to subsidize the processor's risk on premium cards." },
  { term: "Tiered Pricing", definition: "Transactions are bucketed into Qualified, Mid-Qualified, and Non-Qualified tiers. Processors control which tier a transaction falls into, making true costs hard to predict." },
  { term: "Basis Points (bps)", definition: "1 basis point = 0.01%. So 50 bps = 0.50%. Used throughout payments to express processing markups, interchange rates, and fee comparisons." },
  { term: "Auth Rate", definition: "The percentage of card transactions that are successfully approved. A 95% auth rate means 5% of attempted sales are declined — directly lost revenue." },
  { term: "Card Present (CP)", definition: "Transactions where the physical card is used — swiped, dipped (chip), or tapped (NFC). Lower fraud risk means lower interchange rates." },
  { term: "Card Not Present (CNP)", definition: "Transactions where the card is not physically present — e-commerce, phone orders, keyed entries. Higher fraud risk means higher interchange rates." },
  { term: "ACH", definition: "Automated Clearing House — bank-to-bank transfers. Priced per transaction (not as a percentage), making ACH much cheaper than cards for large-dollar payments like B2B invoices or rent." },
  { term: "Chargeback", definition: "A forced reversal of a card transaction initiated by the cardholder's bank. Costs include the disputed amount, a processor fee ($15–$35), and labor to respond. Rates above 1% trigger monitoring programs." },
  { term: "PCI DSS", definition: "Payment Card Industry Data Security Standard. A set of security requirements for handling card data. Compliance costs vary based on how much card data you directly handle." },
  { term: "Gateway", definition: "The technology that routes card transactions between your application and the processor. Cresora's embedded orchestration eliminates the need for a separate gateway." },
  { term: "Effective Rate", definition: "Your true all-in cost of accepting payments as a percentage of total volume. Includes processing fees, PCI, chargebacks, gateway — everything. The single most honest comparison metric." },
  { term: "Residual / Rev Share", definition: "The percentage of net processing revenue shared back to the ISV (your platform). Typical splits range from 20–50%. Higher volume and lower risk earn better splits." },
  { term: "Multi-Rail Routing", definition: "Automatically routing transactions through multiple processors to find the best approval rate and lowest cost. If one processor declines, the transaction is retried through an alternate rail." },
  { term: "ISV", definition: "Independent Software Vendor — a company that builds software with embedded payments. If your platform processes payments on behalf of your merchants, you are an ISV." },
  { term: "Funding Speed", definition: "How quickly settled funds reach the merchant's bank account. Industry standard is 2–3 business days. Faster funding improves merchant satisfaction and reduces churn." },
  { term: "LTV (Lifetime Value)", definition: "The total net revenue generated by an average merchant over their full relationship with your platform. Used to quantify the cost of merchant churn." },
];

const faqs = [
  {
    q: "What is the ROI Calculator?",
    a: "The ROI Calculator helps ISVs (Independent Software Vendors) compare their current payment processing costs against Cresora's offering. It models savings across card processing, ACH, chargebacks, auth rate improvements, and more — at both the individual merchant and full portfolio level.",
  },
  {
    q: "How accurate are the savings estimates?",
    a: "The calculator uses your actual inputs to model costs as accurately as possible. However, estimates depend on the data you provide. For a precise quote, contact Cresora with your actual processing statements.",
  },
  {
    q: "What's the difference between the ISV Portfolio and Per Merchant views?",
    a: "The ISV Portfolio tab shows total costs and savings across your entire merchant base. The Per Merchant tab breaks this down to what a single average merchant would see — useful for sales conversations and merchant-facing proposals.",
  },
  {
    q: "Which pricing model should I select?",
    a: "Select the model your current processor uses. IC+ (Interchange Plus) is the most transparent — you see actual interchange plus a markup. Flat Rate charges one percentage on everything. Tiered bucketing (Qualified/Mid/Non-Qualified) is common but opaque. If unsure, check your processing statement or ask your current provider.",
  },
  {
    q: "What is auth rate lift?",
    a: "Auth rate lift is the additional revenue recovered by routing declined transactions through alternate processors. If your current auth rate is 95% and Cresora improves it to 97%, that 2% lift represents transactions (and revenue) that would have been lost.",
  },
  {
    q: "How does Cresora reduce chargebacks?",
    a: "Cresora uses fraud scoring, velocity checks, and 3DS2 authentication orchestration to prevent fraudulent transactions before they become chargebacks. This reduces both the direct chargeback fees and the labor cost of responding to disputes.",
  },
  {
    q: "Can I save or export my calculations?",
    a: "Saved scenarios and PDF/CSV exports are coming in a future update. For now, you can use your browser's print function (Ctrl+P / Cmd+P) to save the results as a PDF.",
  },
];

export default function HelpPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [glossarySearch, setGlossarySearch] = useState("");

  const filteredGlossary = glossary.filter(
    (g) =>
      g.term.toLowerCase().includes(glossarySearch.toLowerCase()) ||
      g.definition.toLowerCase().includes(glossarySearch.toLowerCase())
  );

  return (
    <div className="max-w-3xl mx-auto px-6 py-12">
      <h1 className="text-2xl font-bold text-white mb-1">Help</h1>
      <p className="text-gray-400 text-sm mb-8">
        Learn how to use the ROI Calculator and understand payment processing terms.
      </p>

      {/* Getting Started */}
      <section className="bg-[#003350]/40 border border-[#003350] rounded-2xl p-6 mb-6">
        <h2 className="text-lg font-semibold text-white mb-3">Getting Started</h2>
        <ol className="space-y-3 text-sm text-gray-300">
          <li className="flex gap-3">
            <span className="flex-shrink-0 w-6 h-6 rounded-full bg-[#FC6200]/20 text-[#FC6200] text-xs font-bold flex items-center justify-center">1</span>
            <span><strong className="text-white">Enter your portfolio size</strong> — Start with the number of merchants on your platform and their average monthly volume and transaction counts.</span>
          </li>
          <li className="flex gap-3">
            <span className="flex-shrink-0 w-6 h-6 rounded-full bg-[#FC6200]/20 text-[#FC6200] text-xs font-bold flex items-center justify-center">2</span>
            <span><strong className="text-white">Set your current pricing</strong> — Select your pricing model (IC+, Flat Rate, or Tiered) and enter your current rates. Check your processing statement for exact numbers.</span>
          </li>
          <li className="flex gap-3">
            <span className="flex-shrink-0 w-6 h-6 rounded-full bg-[#FC6200]/20 text-[#FC6200] text-xs font-bold flex items-center justify-center">3</span>
            <span><strong className="text-white">Review the comparison</strong> — The calculator shows side-by-side costs for your current processor vs. Cresora, including savings from auth rate lift, chargeback reduction, and faster funding.</span>
          </li>
          <li className="flex gap-3">
            <span className="flex-shrink-0 w-6 h-6 rounded-full bg-[#FC6200]/20 text-[#FC6200] text-xs font-bold flex items-center justify-center">4</span>
            <span><strong className="text-white">Switch between views</strong> — Use the ISV Portfolio tab for total impact and the Per Merchant tab for individual merchant economics.</span>
          </li>
        </ol>
        <p className="text-xs text-gray-500 mt-4">
          Hover over the <span className="text-[#68DDDC]">ⓘ</span> icons next to any input for detailed explanations of what each field means.
        </p>
      </section>

      {/* FAQ */}
      <section className="bg-[#003350]/40 border border-[#003350] rounded-2xl p-6 mb-6">
        <h2 className="text-lg font-semibold text-white mb-4">Frequently Asked Questions</h2>
        <div className="space-y-2">
          {faqs.map((faq, i) => (
            <div key={i} className="border border-[#003350] rounded-lg overflow-hidden">
              <button
                onClick={() => setOpenFaq(openFaq === i ? null : i)}
                className="w-full flex items-center justify-between px-4 py-3 text-left text-sm font-medium text-white hover:bg-[#003350]/50 transition-colors"
              >
                {faq.q}
                <svg
                  width="16"
                  height="16"
                  viewBox="0 0 16 16"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  className={`flex-shrink-0 ml-2 text-gray-400 transition-transform ${openFaq === i ? "rotate-180" : ""}`}
                >
                  <path d="M4 6l4 4 4-4" />
                </svg>
              </button>
              {openFaq === i && (
                <div className="px-4 pb-3 text-sm text-gray-300 border-t border-[#003350]">
                  <p className="pt-3">{faq.a}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* Glossary */}
      <section className="bg-[#003350]/40 border border-[#003350] rounded-2xl p-6 mb-6">
        <h2 className="text-lg font-semibold text-white mb-1">Glossary</h2>
        <p className="text-gray-400 text-xs mb-4">Payment processing terms used in the calculator.</p>
        <input
          type="text"
          placeholder="Search terms..."
          value={glossarySearch}
          onChange={(e) => setGlossarySearch(e.target.value)}
          className="w-full bg-[#00273B] border border-[#003350] rounded-lg px-4 py-2.5 text-white text-sm placeholder:text-gray-500 focus:outline-none focus:border-[#68DDDC]/50 focus:ring-1 focus:ring-[#68DDDC]/30 transition-colors mb-4"
        />
        <div className="space-y-3 max-h-[500px] overflow-y-auto pr-1">
          {filteredGlossary.map((g) => (
            <div key={g.term} className="border-b border-[#003350]/60 pb-3 last:border-0">
              <dt className="text-sm font-medium text-[#68DDDC]">{g.term}</dt>
              <dd className="text-sm text-gray-300 mt-0.5">{g.definition}</dd>
            </div>
          ))}
          {filteredGlossary.length === 0 && (
            <p className="text-sm text-gray-500 text-center py-4">No matching terms found.</p>
          )}
        </div>
      </section>

      {/* Contact */}
      <section className="bg-[#003350]/40 border border-[#003350] rounded-2xl p-6">
        <h2 className="text-lg font-semibold text-white mb-1">Contact Support</h2>
        <p className="text-gray-400 text-xs mb-4">Need help or want a custom analysis?</p>
        <div className="flex flex-col sm:flex-row gap-3">
          <a
            href="mailto:support@cresora.com"
            className="inline-flex items-center justify-center gap-2 px-5 py-2.5 bg-[#FC6200] text-white text-sm font-medium rounded-lg hover:bg-[#FC6200]/90 transition-colors"
          >
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
              <rect x="1.5" y="3" width="13" height="10" rx="1.5" />
              <path d="M1.5 4.5L8 9l6.5-4.5" />
            </svg>
            Email Support
          </a>
          <a
            href="https://cresora.com"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center justify-center gap-2 px-5 py-2.5 border border-[#003350] text-gray-300 text-sm font-medium rounded-lg hover:bg-[#003350]/50 hover:text-white transition-colors"
          >
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="8" cy="8" r="6.5" />
              <path d="M1.5 8h13M8 1.5C9.5 3.5 10.25 5.75 10.25 8S9.5 12.5 8 14.5M8 1.5C6.5 3.5 5.75 5.75 5.75 8S6.5 12.5 8 14.5" />
            </svg>
            Visit Cresora.com
          </a>
        </div>
      </section>
    </div>
  );
}
